# Generated by Django 5.2.15 on 2026-06-29 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('rtsp_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_gate', models.CharField(blank=True, max_length=100)),
                ('assigned_hostel', models.CharField(blank=True, max_length=100)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(default='1920x1080', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
