# Generated by Django 5.2.15 on 2026-07-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardens', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardenprofile',
            name='is_main_warden',
            field=models.BooleanField(default=False),
        ),
    ]
