# Generated by Django 5.2.15 on 2026-07-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardens', '0003_wardenprofile_is_main_warden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardenprofile',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
