# Generated by Django 5.2.15 on 2026-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardens', '0004_alter_wardenprofile_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardenprofile',
            name='assigned_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
