# Generated by Django 5.2.15 on 2026-07-15 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Main Campus', max_length=100)),
                ('campus_wifi_ssid', models.CharField(blank=True, max_length=100)),
                ('campus_latitude', models.FloatField(blank=True, null=True)),
                ('campus_longitude', models.FloatField(blank=True, null=True)),
                ('geofence_radius_meters', models.FloatField(default=100.0)),
            ],
            options={
                'verbose_name': 'Campus Settings',
                'verbose_name_plural': 'Campus Settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
