# Generated by Django 5.2.15 on 2026-06-29 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App'), ('PUSH', 'Push Notification'), ('LATE_ALERT', 'Late Return Alert'), ('OUTPASS_STATUS', 'Outpass Status'), ('SYSTEM_ALERT', 'System Alert')], default='IN_APP', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('related_outpass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outpass.outpass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
