# Generated by Django 5.2.15 on 2026-07-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('OUTPASS', 'Outpass'), ('QR', 'QR Code'), ('SECURITY', 'Security'), ('CAMERA', 'Camera'), ('SYSTEM', 'System'), ('SHIFT', 'Shift'), ('MOVEMENT', 'Movement'), ('DETECTION', 'Detection')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20),
        ),
    ]
