# Generated by Django 5.2.15 on 2026-06-29 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('wardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outpass_type', models.CharField(choices=[('REGULAR', 'Regular'), ('EMERGENCY', 'Emergency'), ('WEEKEND', 'Weekend')], default='REGULAR', max_length=20)),
                ('reason', models.TextField()),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('exit_date', models.DateField()),
                ('exit_time', models.TimeField()),
                ('expected_return_date', models.DateField()),
                ('expected_return_time', models.TimeField()),
                ('actual_exit_time', models.DateTimeField(blank=True, null=True)),
                ('actual_return_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active (Exited)'), ('RETURNED', 'Returned'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('warden_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outpasses', to='wardens.wardenprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpasses', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Outpass',
                'verbose_name_plural': 'Outpasses',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
