# Generated by Django 5.2.15 on 2026-07-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpass',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active (Exited)'), ('RETURNED', 'Returned'), ('EXPIRED', 'Expired'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
    ]
