# Generated by Django 5.2.15 on 2026-07-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0002_alter_outpass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='auto_detect_method',
            field=models.CharField(blank=True, choices=[('wifi', 'WiFi'), ('geofence', 'Geofence'), ('manual_scan', 'Manual Scan')], max_length=20, null=True),
        ),
    ]
