# Generated by Django 5.2.15 on 2026-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0003_outpass_auto_detect_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
