// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:1062082582966:web:a06458539525b94b4dc917',
    messagingSenderId: '1062082582966',
    projectId: 'curfew-cam',
    authDomain: 'curfew-cam.firebaseapp.com',
    storageBucket: 'curfew-cam.firebasestorage.app',
    measurementId: 'G-TVK0M2D39D',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:1062082582966:android:f8697321cdb2778e4dc917',
    messagingSenderId: '1062082582966',
    projectId: 'curfew-cam',
    storageBucket: 'curfew-cam.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:1062082582966:ios:c930e2ce1d33bece4dc917',
    messagingSenderId: '1062082582966',
    projectId: 'curfew-cam',
    storageBucket: 'curfew-cam.firebasestorage.app',
    iosBundleId: 'com.curfewcam.curfewcamMobile',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:1062082582966:ios:c930e2ce1d33bece4dc917',
    messagingSenderId: '1062082582966',
    projectId: 'curfew-cam',
    storageBucket: 'curfew-cam.firebasestorage.app',
    iosBundleId: 'com.curfewcam.curfewcamMobile',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:1062082582966:web:3bdd99f7798e73184dc917',
    messagingSenderId: '1062082582966',
    projectId: 'curfew-cam',
    authDomain: 'curfew-cam.firebaseapp.com',
    storageBucket: 'curfew-cam.firebasestorage.app',
    measurementId: 'G-CZ9JH3MPGJ',
  );
}
