# Generated by Django 5.2.15 on 2026-07-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
