# Generated by Django 5.2.15 on 2026-07-17 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_current_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('register_number', models.CharField(max_length=30, unique=True)),
                ('room_number', models.CharField(max_length=20)),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_whitelist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Whitelist',
                'verbose_name_plural': 'Student Whitelists',
                'ordering': ['-created_at'],
            },
        ),
    ]
