# Generated by Django 5.2.15 on 2026-07-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwhitelist',
            name='block',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
