# Generated by Django 5.2.15 on 2026-07-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentwhitelist_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('warden', 'Warden'), ('watchman', 'Watchman'), ('admin', 'Admin'), ('admin_warden', 'Admin Warden')], default='student', max_length=20),
        ),
    ]
