# Generated by Django 5.2.15 on 2026-07-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token for push notifications.', max_length=255, null=True),
        ),
    ]
