# Generated by Django 5.2.15 on 2026-08-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentwhitelist',
            old_name='block',
            new_name='hostel_block',
        ),
        migrations.AddField(
            model_name='studentwhitelist',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='studentwhitelist',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
