# Generated by Django 5.2.15 on 2026-06-29 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchmanProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('assigned_gate', models.CharField(max_length=100)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchman_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('gate', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('watchman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='watchmen.watchmanprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GateScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_type', models.CharField(choices=[('EXIT', 'Exit'), ('RETURN', 'Return')], max_length=10)),
                ('gate', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('qr_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qr.qrpass')),
                ('watchman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='watchmen.watchmanprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
