# Generated by Django 5.2.15 on 2026-07-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_on_campus',
            field=models.BooleanField(default=True),
        ),
    ]
