# Generated by Django 5.2.15 on 2026-07-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_is_on_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
