# Generated by Django 5.2.15 on 2026-06-29 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outpass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=512, unique=True)),
                ('hmac_signature', models.CharField(max_length=128)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('max_scans', models.PositiveIntegerField(default=1)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('outpass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_pass', to='outpass.outpass')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
